# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Better Millennial
email: jscho13@gmail.com
tagline: 'Because Everyday Is Another Opportunity'
description: 'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
github_username:  jscho13
paginate:         5
author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Build settings
markdown: kramdown
# theme: minima

# Lyson Dependencies
# markdown:         redcarpet
# highlighter:         pygments
# Lyson  Permalinks
permalink:        pretty
