# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dedd23d98c9ae02a9438263ab952f26e195603e3f4b371557b8aa6ed9bf8d1b6db7d5eaf39a49c0e384f570ec29667a21b7e885bfcec54b41886d15d3e54840

test:
  secret_key_base: b0d0bde2190faa858e7be396bbd2fe9d2abb74350f51354283ec107d8e25d340cb1fc06bf9de72f8dbe22dccc611b4db0a624733baad884cfed3d4a2893ad64d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
