# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 594e3636289be1269943e3e7b06a635b2dd083d52bee6b3ed690478afff8e35c49a3f160953f0705460d594253372324a1fb9aefba2c8ec58cd72fc7ad3069bf

test:
  secret_key_base: b214bc5914d6ec3f7195c5a0b20e8284f4b020a9c7704ee9c9885151d994c11847bea4994602411fead016cfa6bbff3706f8c636bf4630ab5486f5c374b96e70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
